### ISSUE TITLE
How to install on HA V6.1

### ISSUE THREAD

**Issue by jalicz** [soldag/python-pwmled#5]
I have Home Assistant OS 6.1 installed on my RPi4 + 4Gig.

Here is :
https://www.home-assistant.io/integrations/rpi_gpio_pwm/
On Raspbian Jessie 2016-05-10 or newer the pigpio library is already included.

Include HA 6.1 this library ?

I'm trying to install, but the SSH Terminal is not possible to use commands sudo, make, etc
I don't know how to do the installation

If the library is part of how it is possible to start this daemon ?

setting :
light:
  - platform: rpi_gpio_pwm
    leds:
      - name: vetrak RPI
        driver: gpio
        pins: [17]
        type: simple 

logs :
Error while setting up rpi_gpio_pwm platform for light

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/rpi_gpio_pwm/light.py", line 82, in setup_platform
    driver = GpioDriver(pins, **opt_args)
  File "/usr/local/lib/python3.8/site-packages/pwmled/driver/gpio.py", line 25, in __init__
    raise ConnectionError('Could not connect to the pigpio daemon')
ConnectionError: Could not connect to the pigpio daemon

Thanks JALI

**Comment by soldag** [comment]
Hi @jalicz, I never worked with Home Assistant OS so far, but there is a pigpio plugin which should fix your problem. Check out https://community.home-assistant.io/t/pigpio-addon/314734

**Comment by soldag** [comment]
Closed as I never got a response back
