### ISSUE TITLE
Compatibility with different `adafruit-blinka` versions?

### ISSUE THREAD

**Issue by cdce8p** [soldag/python-pwmled#6]
Would it be possible to relax the requirements for at least `adafruit-blinka`? It's currently pinned to `==5.5.1` which can cause conflicting dependencies. Especially with regards to Home Assistant.

https://github.com/soldag/python-pwmled/blob/43e164d26ce0306218455a3814ec80040c491e36/setup.py#L18-L23

From what I've seen the major version jump was mainly to drop some Python versions. That wouldn't be an issue though, since pip can automatically choose a supported version given a range. If possible, changing it to `>=5.5.1` or `>=5.5.1,<7.0` would help. Thanks!
https://github.com/adafruit/Adafruit_Blinka/compare/5.5.1...6.18.0

**Comment by soldag** [comment]
Hey @cdce8p, thanks for reporting the issue. It has been fixed in v1.6.9.

**Comment by cdce8p** [comment]
Thanks @soldag! I already opened a PR to update the dependency in Home-Assistant: https://github.com/home-assistant/core/pull/65465
