### ISSUE TITLE
Where's the source for 1.6.10 ?

### ISSUE THREAD

**Issue by onkelbeh** [soldag/python-pwmled#8]

**Comment by onkelbeh** [comment]
I'll take https://github.com/soldag/python-pwmled/commit/0dcf80fe05bf30098a7d3cc1e31b837fcce19469 for now. Hope it's correct :-)

**Comment by soldag** [comment]
Ah, seems I forgot to push the tag back then. Thanks for pointing out. 0dcf80f was correct though 👍
